[versions]
slf4j-version = "2.0.0-alpha5"
log4j2-version = "2.17.0"
log4j2-slf4j-version = "2.17.0"
picocli-version = "4.6.2"
jackson-version = "2.13.0"
jakarta-mail-version = "2.0.1"
selenide-version = "6.1.1"
jetbrains-annotations-version = "23.0.0"

shadow-version = "7.1.1"
names-version = "0.39.0"
lombok-version = "6.3.0"
jib-version = "3.1.4"

[libraries]
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j-version" }
log4j2-core = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j2-version" }
log4j2-slf4j = { group = "org.apache.logging.log4j", name = "log4j-slf4j18-impl", version.ref = "log4j2-slf4j-version" }
picocli = { group = "info.picocli", name = "picocli", version.ref = "picocli-version" }
jackson-core = { group = "com.fasterxml.jackson.core", name = "jackson-core", version.ref = "jackson-version" }
jackson-annotations = { group = "com.fasterxml.jackson.core", name = "jackson-annotations", version.ref = "jackson-version" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson-version" }
jakartaMail = { group = "com.sun.mail", name = "jakarta.mail", version.ref = "jakarta-mail-version" }
selenide = { group = "com.codeborne", name = "selenide", version.ref = "selenide-version" }
jetbrainsAnnotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrains-annotations-version" }

[bundles]
jackson = ["jackson-core", "jackson-annotations", "jackson-databind"]
log4j2 = ["log4j2-core", "log4j2-slf4j"]

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow-version" }
names = { id = "com.github.ben-manes.versions", version.ref = "names-version" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok-version" }
jib = { id = "com.google.cloud.tools.jib", version.ref = "jib-version" }
