[versions]
slf4j-version = "2.0.0-alpha3"
log4j2-version = "2.14.1"
log4j2-slf4j-version = "2.14.1"
logback-version = "1.3.0-alpha4"
picocli-version = "4.6.1"
jackson-version = "2.12.3"
jakarta-mail-version = "2.0.1"
selenide-version = "5.23.2"

[libraries]
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j-version" }
log4j2-core = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j2-version" }
log4j2-slf4j = { group = "org.apache.logging.log4j", name = "log4j-slf4j18-impl", version.ref = "log4j2-slf4j-version" }
logback = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback-version" }
picocli = { group = "info.picocli", name = "picocli", version.ref = "picocli-version" }
jackson-core = { group = "com.fasterxml.jackson.core", name = "jackson-core", version.ref = "jackson-version" }
jackson-annotations = { group = "com.fasterxml.jackson.core", name = "jackson-annotations", version.ref = "jackson-version" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson-version" }
jakartaMail = { group = "com.sun.mail", name = "jakarta.mail", version.ref = "jakarta-mail-version" }
selenide = { group = "com.codeborne", name = "selenide", version.ref = "selenide-version" }

[bundles]
jackson = ["jackson-core", "jackson-annotations", "jackson-databind"]
log4j2 = ["log4j2-core", "log4j2-slf4j"]
